package pt.unl.fct.iadi.novaevents.weather

import org.springframework.web.service.annotation.GetExchange
import org.springframework.web.service.annotation.HttpExchange

/**
 * Declarative HTTP client for OpenWeatherMap's current-weather endpoint.
 * The concrete implementation is generated by Spring from a [org.springframework.web.client.RestClient]
 * (see [WeatherClientConfig]).
 */
@HttpExchange(url = "/data/2.5")
interface OpenWeatherClient {

    @GetExchange("/weather")
    fun getCurrentWeather(
        @org.springframework.web.bind.annotation.RequestParam("q") location: String,
        @org.springframework.web.bind.annotation.RequestParam("appid") apiKey: String,
        @org.springframework.web.bind.annotation.RequestParam("units") units: String = "metric"
    ): WeatherResponse
}
